### ISSUE TITLE
Failed to call RegisterHub above Android 31

### ISSUE THREAD

**Issue by jhoonPark** [yoctopuce/yoctolib_android#1]
Hi, I'm currently using YoctoLib v1.10.49504 by AAR.
Above Android 31, Android throws an error related with PendingIntent.

You can see full error logs below, so please check this issue.

```
2022-04-26 15:13:56.363 29806-29806/com.xxx E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxx, PID: 29806
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx/com.xxx.MainActivity}: java.lang.IllegalArgumentException: com.xxx: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4035)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8663)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
     Caused by: java.lang.IllegalArgumentException: com.xxx: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:673)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:660)
        at com.yoctopuce.YoctoAPI.YUSBHub.doPermissionRequest(YUSBHub.java:220)
        at com.yoctopuce.YoctoAPI.YUSBHub.requestUSBPermission(YUSBHub.java:208)
        at com.yoctopuce.YoctoAPI.YUSBRawDevice.ensureIOStarted(YUSBRawDevice.java:151)
        at com.yoctopuce.YoctoAPI.YUSBHub.refreshUsableDeviceList(YUSBHub.java:261)
        at com.yoctopuce.YoctoAPI.YUSBHub.updateDeviceList(YUSBHub.java:293)
        at com.yoctopuce.YoctoAPI.YAPIContext._updateDeviceList_internal(YAPIContext.java:756)
        at com.yoctopuce.YoctoAPI.YAPIContext.RegisterHub(YAPIContext.java:1174)
        at com.yoctopuce.YoctoAPI.YAPI.RegisterHub(YAPI.java:408)
        at com.xxx.util.YoctoRelay.<init>(YoctoRelay.kt:22)
        at com.xxx.BaseActivity.onCreate(BaseActivity.kt:136)
        at com.xxx.MainActivity.onCreate(MainActivity.kt:76)
        at android.app.Activity.performCreate(Activity.java:8290)
        at android.app.Activity.performCreate(Activity.java:8270)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009)
        	... 12 more
2022-04-26 15:13:56.375 29806-29806/? I/Process: Sending signal. PID: 29806 SIG: 9
```

Best regard
jhoonPark

**Comment by jhoonPark** [comment]
also, I found that YAPI.RegisterDeviceArribalCallback only return YModule.
is there any way to convert YModule to YRelay?
I need to find & use YRelay but YModule.hardwardId is different from YRelay.hardwardId

**Comment by srinsoz** [comment]
Hi, I just released a new build with a fix for the PendingIntent. You just need to update the Yoctpuce Library of
Your project and everything should work as expected.

Regarding the module vs. YRelay comment, I suspect that you do not full understand how our API works. You should
Read our tutorial on how our API is structured: https://www.yoctopuce.com/EN/article/logical-structure-of-yoctopuce-devices

Also, if you want an example of usage of YAPI.RegisterDeviceArribalCallback you can have a look at the Doc-Example that is included in our library. The file Examples/Doc-Examples/src/main/java/com/yoctopuce/doc_examples/ProgEventBasedFragment.java is what you are searching for.

**Comment by jhoonPark** [comment]
Thank you! I'll apply updated library and also read commented tutorial documentation.
