### ISSUE TITLE
Android 34 registerReceiver problem

### ISSUE THREAD

**Issue by AntonEvmenenko** [yoctopuce/yoctolib_android#2]
Hello,

First, thank you for this library! I'm using it to work with Yocto-Thermocouple on Android and I'm happy with it.

Unfortunately, recently I got a problem. I updated my Android tablet to API 34, and now my app is crashing because of the following error:

```
java.lang.SecurityException: com.aaa.bbb.myapp.debug: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
	at android.os.Parcel.createException(Parcel.java:3053)
	at android.os.Parcel.readException(Parcel.java:3036)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6137)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1913)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1853)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1841)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:772)
	at com.yoctopuce.YoctoAPI.YUSBHub.<init>(YUSBHub.java:167)
	...
```

As far as I understand, it's super easy to fix this problem. You just need to pass either RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED as the last parameter for [this function](https://github.com/yoctopuce/yoctolib_android/blob/3a401f0768cedbc79665b43670261497a96cb002/YoctoLib/src/main/java/com/yoctopuce/YoctoAPI/YUSBHub.java#L167).

Can you please add this change and upload the new version? If not, any information on how to build the .aar would also help a lot, as I can easily introduce this fix myself, but it's not clear for me how to build the library.

Thank you so much in advance!

**Comment by AntonEvmenenko** [comment]
I tried passing RECEIVER_EXPORTED to [sAppContext.registerReceiver](https://github.com/yoctopuce/yoctolib_android/blob/3a401f0768cedbc79665b43670261497a96cb002/YoctoLib/src/main/java/com/yoctopuce/YoctoAPI/YUSBHub.java#L167) as the third parameter, and it works. Just FYI
